name: OmGames
version: '0.0.0.0.0.5'
main: krispasi.omGames.OmGames
api-version: '1.21'
commands:
  bw:
    description: BedWars admin commands
    usage: /bw start
    permission: omgames.bw
    permission-message: You need omgames.bw to manage BedWars.
