name: OmGames
version: ${project.version}
main: krispasi.omGames.OmGames
api-version: '1.21'
commands:
  bw:
    description: BedWars commands
    usage: /bw start | /bw stop | /bw setup new <arena> | /bw setup <arena> [key]
    permission: omgames.bw.start
permissions:
  omgames.bw.start:
    description: Allows opening the BedWars setup GUI
    default: op
  omgames.bw.setup:
    description: Allows configuring BedWars arenas via /bw setup
    default: op
