id: alchemy_cauldron
name: "Alchemy Cauldron"
size: medium
blueprint: alchemy_cauldron_blueprint
implemented: true
levels:
  1:
    parts:
      - material: CAULDRON
        offset: [0, 0, 0]
        scale: [1, 1, 1]
      - material: BREWING_STAND
        offset: [0.9, 0, 0]
        scale: [0.7, 0.7, 0.7]
  2:
    upgrade-cost: {diamond: 4}
    parts:
      - material: WATER_CAULDRON
        block-data: "level=2"
        offset: [0, 0, 0]
        scale: [1.05, 1.05, 1.05]
      - material: BREWING_STAND
        offset: [0.9, 0, 0]
        scale: [0.8, 0.8, 0.8]
  3:
    upgrade-cost: {diamond: 8}
    parts:
      - material: WATER_CAULDRON
        block-data: "level=3"
        offset: [0, 0, 0]
        scale: [1.1, 1.1, 1.1]
      - material: BREWING_STAND
        offset: [0.95, 0, 0]
        scale: [0.9, 0.9, 0.9]
