id: bounty_board
name: "Bounty Board"
size: medium
blueprint: bounty_board_blueprint
implemented: false
levels:
  1:
    upgrade-cost: {wood: 4, redstone: 1}
    parts:
      - material: OAK_PLANKS
        offset: [0, 0.2, 0]
        scale: [1.5, 1, 0.2]
  2:
    upgrade-cost: {wood: 6, redstone: 3}
    parts:
      - material: OAK_PLANKS
        offset: [0, 0.25, 0]
        scale: [1.8, 1.15, 0.2]
      - material: LANTERN
        offset: [0.8, 0.75, 0]
        scale: [0.4, 0.4, 0.4]
  3:
    parts:
      - material: OAK_PLANKS
        offset: [0, 0.25, 0]
        scale: [2, 1.25, 0.2]
      - material: LANTERN
        offset: [0.8, 0.8, 0]
        scale: [0.45, 0.45, 0.45]
