id: carrot_farm
name: "Carrot Farm"
size: small
blueprint: carrot_farm_blueprint
implemented: true
levels:
  1:
    harvest:
      uses: 1
      items:
        - carrot
    parts:
      - material: FARMLAND
        offset: [0, 0, 0]
        scale: [1, 0.25, 1]
      - material: CARROTS
        block-data: "age=5"
        offset: [0.1, 0.25, 0.1]
        scale: [0.8, 0.8, 0.8]
    empty-parts:
      - material: FARMLAND
        offset: [0, 0, 0]
        scale: [1, 0.25, 1]
  2:
    upgrade-cost: {diamond: 2}
    harvest:
      uses: 2
      items:
        - carrot
    parts:
      - material: FARMLAND
        offset: [0, 0, 0]
        scale: [1, 0.25, 1]
      - material: CARROTS
        block-data: "age=7"
        offset: [0.1, 0.25, 0.1]
        scale: [0.9, 0.9, 0.9]
      - material: CARROTS
        block-data: "age=6"
        offset: [-0.25, 0.25, -0.15]
        scale: [0.7, 0.7, 0.7]
    empty-parts:
      - material: FARMLAND
        offset: [0, 0, 0]
        scale: [1, 0.25, 1]
  3:
    upgrade-cost: {diamond: 4}
    harvest:
      uses: 3
      items:
        - carrot
        - carrot
    parts:
      - material: FARMLAND
        offset: [0, 0, 0]
        scale: [1.1, 0.25, 1.1]
      - material: CARROTS
        block-data: "age=7"
        offset: [0.15, 0.25, 0.1]
        scale: [1.0, 1.0, 1.0]
      - material: CARROTS
        block-data: "age=7"
        offset: [-0.2, 0.25, -0.2]
        scale: [0.85, 0.85, 0.85]
    empty-parts:
      - material: FARMLAND
        offset: [0, 0, 0]
        scale: [1.1, 0.25, 1.1]
